/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import Entitas.Mahasiswa;
import Services.ServiceMahasiswa;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngadmin
 */
public class DataMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form DataMahasiswa
     */
    final ServiceMahasiswa serviceMahasiswa;

    public DataMahasiswa() throws RemoteException, NotBoundException {
        Registry registry = LocateRegistry.getRegistry(1099);
        serviceMahasiswa = (ServiceMahasiswa) registry.lookup("mahasiswa");
        initComponents();
        select(serviceMahasiswa);
    }

    @SuppressWarnings("empty-statement")

    private void select(ServiceMahasiswa serviceMahasiswa1) throws RemoteException {
        List listMahasiswa = new ArrayList<>();

        String header[] = {"NIM", "NAMA", "PRODI"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(null, header);
        tabelMahasiswa.setModel(defaultTableModel);

        for (int i = 0; i < tabelMahasiswa.getRowCount(); i++) {
            defaultTableModel.removeRow(i);
        }
        listMahasiswa = serviceMahasiswa1.getMahasiswa();
        for (int i = 0; i < listMahasiswa.size(); i++) {
            Object baris[] = {listMahasiswa.get(i).getNim(), listMahasiswa.get(i).getNama(), listMahasiswa.get(i).getProdi()};
            defaultTableModel.addRow(baris);
        }
    }

    private void insert(ServiceMahasiswa serviceMahasiswa1) throws RemoteException {

        Mahasiswa m = new Mahasiswa();
        m.setNim(txtNim.getText());
        m.setNama(txtNama.getText());
        m.setProdi(Prodi.getSelectedItem().toString());
        serviceMahasiswa1.insert(m);
    }

    private void update(ServiceMahasiswa serviceMahasiswa1) throws RemoteException {

        Mahasiswa m = new Mahasiswa();
        m.setNim(txtNim.getText());
        m.setNama(txtNama.getText());
        m.setProdi(Prodi.getSelectedItem().toString());
        serviceMahasiswa1.update(m);

    }

    private void delete(ServiceMahasiswa serviceMahasiswa1) throws RemoteException {
        Mahasiswa m = new Mahasiswa();
        m.setNim(txtNim.getText());
        serviceMahasiswa1.delete(m);
    }

    private void clear() {
        txtNim.setText("");
        txtNama.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelMahasiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMahasiswa;
    // End of variables declaration//GEN-END:variables
}
